# Generated by Django 5.2.5 on 2025-08-20 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.PositiveIntegerField(blank=True, null=True)),
                ('composition_id', models.PositiveIntegerField(blank=True, null=True)),
                ('tempo', models.FloatField()),
                ('key', models.CharField(max_length=10)),
                ('mode', models.IntegerField(help_text='0 for minor, 1 for major')),
                ('acousticness', models.FloatField(default=0.0)),
                ('danceability', models.FloatField(default=0.0)),
                ('energy', models.FloatField(default=0.0)),
                ('instrumentalness', models.FloatField(default=0.0)),
                ('liveness', models.FloatField(default=0.0)),
                ('loudness', models.FloatField(default=0.0)),
                ('speechiness', models.FloatField(default=0.0)),
                ('valence', models.FloatField(default=0.0)),
                ('spectral_centroid', models.JSONField(default=list)),
                ('mfcc', models.JSONField(default=list, help_text='Mel-frequency cepstral coefficients')),
                ('chroma', models.JSONField(default=list)),
                ('spectral_rolloff', models.JSONField(default=list)),
                ('zero_crossing_rate', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tempo'], name='audio_proce_tempo_3ebf83_idx'), models.Index(fields=['key'], name='audio_proce_key_172648_idx'), models.Index(fields=['danceability'], name='audio_proce_danceab_832aea_idx'), models.Index(fields=['energy'], name='audio_proce_energy_73fc2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AudioProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_type', models.CharField(choices=[('spectrum_analysis', 'Spectrum Analysis'), ('beat_detection', 'Beat Detection'), ('mood_analysis', 'Mood Analysis'), ('visualization', 'Audio Visualization'), ('feature_extraction', 'Feature Extraction')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('audio_file', models.FileField(upload_to='processing/input/')),
                ('parameters', models.JSONField(default=dict)),
                ('result_data', models.JSONField(default=dict)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='processing/output/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audio_proce_user_id_7ddfc9_idx'), models.Index(fields=['status', '-created_at'], name='audio_proce_status_f9e8fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='AudioVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('frequency_data', models.JSONField(help_text='Frequency spectrum data')),
                ('amplitude_data', models.JSONField(help_text='Amplitude over time')),
                ('beat_data', models.JSONField(help_text='Beat detection data')),
                ('visualization_type', models.CharField(default='spectrum', max_length=50)),
                ('color_scheme', models.CharField(default='default', max_length=50)),
                ('sensitivity', models.FloatField(default=1.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session_id', '-timestamp'], name='audio_proce_session_3297f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='RealtimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('processing_type', models.CharField(max_length=50)),
                ('channel_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-last_activity'], name='audio_proce_user_id_8f4e5d_idx'), models.Index(fields=['is_active', '-last_activity'], name='audio_proce_is_acti_d09f2d_idx')],
            },
        ),
    ]
