# Generated by Django 5.2.5 on 2025-08-20 21:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'service_name')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('composition_created', 'Created Composition'), ('composition_liked', 'Liked Composition'), ('user_followed', 'Followed User'), ('collaboration_joined', 'Joined Collaboration'), ('playlist_created', 'Created Playlist'), ('track_streamed', 'Streamed Track')], max_length=30)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional activity data')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='authenticat_user_id_9383ee_idx'), models.Index(fields=['activity_type', '-created_at'], name='authenticat_activit_990d67_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['follower', 'created_at'], name='authenticat_followe_486f94_idx'), models.Index(fields=['following', 'created_at'], name='authenticat_followi_706436_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('favorite_genres', models.JSONField(default=list, help_text='List of favorite music genres')),
                ('music_experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], default='beginner', max_length=20)),
                ('preferred_instruments', models.JSONField(default=list, help_text='List of preferred instruments')),
                ('is_public', models.BooleanField(default=True, help_text='Profile visibility')),
                ('allow_collaboration', models.BooleanField(default=True)),
                ('receive_notifications', models.BooleanField(default=True)),
                ('ai_creativity_level', models.FloatField(default=0.7, help_text='AI creativity preference (0-1)')),
                ('preferred_ai_models', models.JSONField(default=list, help_text='Preferred AI model versions')),
                ('total_compositions', models.PositiveIntegerField(default=0)),
                ('total_collaborations', models.PositiveIntegerField(default=0)),
                ('reputation_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['reputation_score'], name='authenticat_reputat_7bc831_idx'), models.Index(fields=['last_active'], name='authenticat_last_ac_de606c_idx')],
            },
        ),
    ]
