# Generated by Django 5.2.5 on 2025-08-20 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tempo', models.CharField(choices=[('slow', 'Slow (60-90 BPM)'), ('moderate', 'Moderate (90-120 BPM)'), ('fast', 'Fast (120-160 BPM)'), ('very_fast', 'Very Fast (160+ BPM)')], default='moderate', max_length=20)),
                ('key_signature', models.CharField(choices=[('C', 'C Major'), ('Am', 'A Minor'), ('G', 'G Major'), ('Em', 'E Minor'), ('D', 'D Major'), ('Bm', 'B Minor'), ('A', 'A Major'), ('F#m', 'F# Minor'), ('E', 'E Major'), ('C#m', 'C# Minor'), ('B', 'B Major'), ('G#m', 'G# Minor'), ('F#', 'F# Major'), ('D#m', 'D# Minor'), ('F', 'F Major'), ('Dm', 'D Minor'), ('Bb', 'Bb Major'), ('Gm', 'G Minor'), ('Eb', 'Eb Major'), ('Cm', 'C Minor'), ('Ab', 'Ab Major'), ('Fm', 'F Minor'), ('Db', 'Db Major'), ('Bbm', 'Bb Minor'), ('Gb', 'Gb Major'), ('Ebm', 'Eb Minor')], default='C', max_length=10)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('ai_model_version', models.CharField(default='v1.0', max_length=50)),
                ('generation_parameters', models.JSONField(default=dict, help_text='AI model parameters used')),
                ('midi_data', models.TextField(blank=True, help_text='MIDI representation')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='compositions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='composition.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompositionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composition.musiccomposition')),
            ],
        ),
        migrations.AddIndex(
            model_name='musiccomposition',
            index=models.Index(fields=['user', '-created_at'], name='composition_user_id_e3a305_idx'),
        ),
        migrations.AddIndex(
            model_name='musiccomposition',
            index=models.Index(fields=['genre', '-created_at'], name='composition_genre_i_7a48f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compositionlike',
            unique_together={('user', 'composition')},
        ),
    ]
